[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm run build:prod"

[deploy]
startCommand = "pnpm --filter db push-force && pnpm --filter db seed:kerala && node --enable-source-maps ./artifacts/api-server/dist/index.mjs"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
